---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Installing docker
      ansible.builtin.shell: |
        yum update -y
        amazon-linux-extras install docker
        service docker start
        service docker status
        systemctl enable docker
        usermod -a -G docker ec2-user
        systemctl enable docker

    - name: Installing jenkins via docker
      ansible.builtin.shell: |
        docker pull jenkins/jenkins
        docker images

    - name: Stop running docker container
      ansible.builtin.shell: |
        docker stop jenkins
        docker ps
  
    - name: Start docker container
      ansible.builtin.shell: |
        docker run --rm -d --name jenkins -p 8080:8080 -v $PWD/jenkins/ jenkins/jenkins
        docker ps

    - name: Wait until Jenkins is up
      shell: result_first=1; while [[ $result_first != 0 ]]; do if [[ docker logs jenkins | grep 'Jenkins is fully up and running' ]];then result_first=0;else sleep 4;fi;done
      register: result
      until: result.rc == 0
